# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PWR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PWR
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'


  target 'PWRTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PWRUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
