//
//  States.swift
//  PWR
//
//  Created by Amber Spadafora on 10/4/17.
//  Copyright © 2017 Amber Spadafora. All rights reserved.
//

import Foundation

struct States {
    static let stateDictionary: [String : String] = [
        "AK" : "Alaska",
        "AL" : "Alabama",
        "AR" : "Arkansas",
        "AZ" : "Arizona",
        "CA" : "California",
        "CO" : "Colorado",
        "CT" : "Connecticut",
        "DC" : "District of Columbia",
        "DE" : "Delaware",
        "FL" : "Florida",
        "GA" : "Georgia",
        "HI" : "Hawaii",
        "IA" : "Iowa",
        "ID" : "Idaho",
        "IL" : "Illinois",
        "IN" : "Indiana",
        "KS" : "Kansas",
        "KY" : "Kentucky",
        "LA" : "Louisiana",
        "MA" : "Massachusetts",
        "MD" : "Maryland",
        "ME" : "Maine",
        "MI" : "Michigan",
        "MN" : "Minnesota",
        "MO" : "Missouri",
        "MS" : "Mississippi",
        "MT" : "Montana",
        "NC" : "North Carolina",
        "ND" : "North Dakota",
        "NE" : "Nebraska",
        "NH" : "New Hampshire",
        "NJ" : "New Jersey",
        "NM" : "New Mexico",
        "NV" : "Nevada",
        "NY" : "New York",
        "OH" : "Ohio",
        "OK" : "Oklahoma",
        "OR" : "Oregon",
        "PA" : "Pennsylvania",
        "PR" : "Puerto Rico",
        "RI" : "Rhode Island",
        "SC" : "South Carolina",
        "SD" : "South Dakota",
        "TN" : "Tennessee",
        "TX" : "Texas",
        "UT" : "Utah",
        "VA" : "Virginia",
        "VI" : "Virgin Islands",
        "VT" : "Vermont",
        "WA" : "Washington",
        "WI" : "Wisconsin",
        "WV" : "West Virginia",
        "WY" : "Wyoming"]
    
//    static let states = [ "AK",
//                                "AL",
//                                "AR",
//                                "AZ",
//                                "CA",
//                                "CO",
//                                "CT",
//                                "DC",
//                                "DE",
//                                "FL",
//                                "GA",
//                                "GU",
//                                "HI",
//                                "IA",
//                                "ID",
//                                "IL",
//                                "IN",
//                                "KS",
//                                "KY",
//                                "LA",
//                                "MA",
//                                "MD",
//                                "ME",
//                                "MI",
//                                "MN",
//                                "MO",
//                                "MS",
//                                "MT",
//                                "NC",
//                                "ND",
//                                "NE",
//                                "NH",
//                                "NJ",
//                                "NM",
//                                "NV",
//                                "NY",
//                                "OH",
//                                "OK",
//                                "OR",
//                                "PA",
//                                "PR",
//                                "RI",
//                                "SC",
//                                "SD",
//                                "TN",
//                                "TX",
//                                "UT",
//                                "VA",
//                                "VI",
//                                "VT",
//                                "WA",
//                                "WI",
//                                "WV",
//                                "WY"]
}
